baseURL: https://tiago.carreira.pw/
# defaultContentLanguage: en
title: "Tiago Carreira"
theme: "toha"

languages:
  en:
    languageName: English
    weight: 1
    languageCode: en-us
  # pt:
  #   languageName: Português
  #   weight: 2
  #   languageCode: pt-pt
  # es:
  #   languageName: Español
  #   weight: 3
  #   languageCode: es-es

outputs:
  home:
    - HTML
    - RSS
    - JSON

# Allow raw html in markdown file
markup:
  goldmark:
    renderer:
      unsafe: true
  tableOfContents:
    startLevel: 2
    endLevel: 6
    ordered: false

enableEmoji: true

# Site parameters
params:

  customJS: 
    - js/custom.js

  background: /images/site/background.jpg

  # Provide logos for your site. The inverted logo will be used in the initial
  # transparent navbar and the main logo will be used in the non-transparent navbar.
  # It will default to the theme logos if not provided.
  logo:
    main: /images/site/main-logo.png
    inverted: /images/site/inverted-logo.png
    favicon: /images/site/favicon.png

  # GitHub repo URL of your site
  gitRepo: https://github.com/tcarreira/tiago.carreira.pw
  gitBranch: main

  # specify whether you want to write some blog posts or not
  enableBlogPost: false

  # specify whether you want to show Table of Contents in reading page
  enableTOC: true

  # Provide newsletter configuration. This feature hasn't been implemented yet.
  # Currently, you can just hide it from the footer.
  newsletter:
    enable: false
