services:
  # needs this on the first run: docker compose run --rm hugo npm ci
  hugo:
    image: hugomods/hugo:ci-non-root-0.146.6
    command: server -D
    volumes:
      - .:/src
      - ~/.cache/hugo_cache:/tmp/hugo_cache
    ports:
      - 1313:1313
